fix: add nil checks for some functions
oras-project/oras-go pull request #327
Opened 2022-09-20 08:54 UTC by jasminetMSFT

Add `nil` checks for functions `oras.WithTargetPlatform`, `oras.FilterAnnotation` and `oras.FilterArtifactType`.

Resolves #318 
Signed-off-by: JasmineTang <jasminetang@microsoft.com>

2022-09-20 09:13 UTC, shizhMSFT commented on extendedcopy.go
> +	if key == "" {
Should we also check `regex`? BTW, is empty key a valid input?

2022-09-20 09:44 UTC, Wwwsylvia commented on copy_test.go
> +	}
We should also test the case where there is a custom `opts.MapRoot`.

2022-09-20 09:44 UTC, Wwwsylvia commented on extendedcopy_test.go
> +func TestExtendedCopyGraph_FilterAnnotationWithNoRegex(t *testing.T) {
Maybe we can merge `TestExtendedCopyGraph_FilterAnnotationWithNoKey` and `TestExtendedCopyGraph_FilterAnnotationWithNoRegex` into `TestExtendedCopyGraph_FilterAnnotation`?

2022-09-20 10:48 UTC, Wwwsylvia requested changes

2022-09-20 10:48 UTC, Wwwsylvia commented on copy.go
> +	if p == nil {
We need to document the nil behavior.

2022-09-21 05:58 UTC, wangxiaoxuan273 commented on extendedcopy.go
> +	if regex == nil {
In the case of `regex == nil`, why does `FilterAnnotation` proceeds filtering, while `FilterArtifactType` just returns ? Should they have the same behavior?

2022-09-21 06:02 UTC, wangxiaoxuan273 commented on extendedcopy_test.go
> +	opts.FilterArtifactType(nil)
I think we can also test the cases of calling `FilterArtifactType` and `FilterAnnotation` **multiple times**, where one or some of the calls have nil arguments.

2022-09-22 07:22 UTC, shizhMSFT requested changes

2022-09-22 07:22 UTC, shizhMSFT commented on extendedcopy.go
> +	if regex == nil {
Let's document this `regex == nil` behavior.

2022-09-22 07:22 UTC, shizhMSFT commented on extendedcopy.go
>  			}
```suggestion
			if value, ok := p.Annotations[key]; ok && (regex == nil || regex.MatchString(value)) {
				filtered = append(filtered, p)
			}
```

2022-09-22 07:55 UTC, shizhMSFT approved these changes
LGTM

2022-09-22 08:22 UTC, Wwwsylvia commented on copy_test.go
> +
Did you forget to call `opts.WithTargetPlatform(nil)`?

2022-09-22 08:22 UTC, Wwwsylvia commented on extendedcopy.go
> +			if value, ok := p.Annotations[key]; ok && (regex == nil || regex.MatchString(value)) {
We need to document this behavior.

2022-09-22 08:22 UTC, Wwwsylvia commented on copy.go
> +// - If the given platform is nil, no operations will be done.
nit: how about "no platform selection will be applied"?

2022-09-22 08:22 UTC, Wwwsylvia commented on extendedcopy.go
> +// no operations will be done. For performance consideration, when using both
nit: how about "no artifact type filter will be applied"?

2022-09-22 09:08 UTC, Wwwsylvia approved these changes
LGTM

2022-09-22 09:14 UTC, shizhMSFT commented on extendedcopy.go
> +// will not be returned.
A predecessor is not filtered out if the key is in its annotation and matches the regex if present.

2022-09-22 09:20 UTC, shizhMSFT approved these changes
LGTM

2022-09-22 09:20 UTC, merged