refactor: return `ErrBadRequest` for manifest push
oras-project/oras-go pull request #351
Opened 2022-10-27 11:35 UTC by Wwwsylvia

Resolves #344
Signed-off-by: Lixia (Sylvia) Lei <lixlei@microsoft.com>

2022-10-27 12:10 UTC, shizhMSFT requested changes

2022-10-27 12:10 UTC, shizhMSFT commented on registry/remote/repository.go
> +		return fmt.Errorf("%s: %s: %w: %v", expected.Digest, expected.MediaType, ErrBadRequest, err)
It is weird to have `ErrBadRequest` here as it cannot indicate invalid manifest.

That is, `MANIFEST_INVALID` implies but is not implied by `400 Bad Request`.

2022-10-27 12:10 UTC, shizhMSFT commented on registry/remote/repository.go
> +		return fmt.Errorf("%s: %s: %w: %v", expected.Digest, expected.MediaType, ErrBadRequest, err)
Furthermore, the `ErrBadRequest` does not contain the context. In other words, we are not able to distinguish a real bad request with an unsupported manifest in a `oras.Copy()` scenario with lots of manifests.

2022-10-28 02:38 UTC, Wwwsylvia commented
Closing this PR as there is a better approach. See https://github.com/opencontainers/distribution-spec/issues/359.

2022-10-28 02:38 UTC, closed without merging