feat: remove AutoRemoveReferrers flag
oras-project/oras-go pull request #683
Opened 2024-01-19 03:09 UTC by wangxiaoxuan273

following #680

2024-01-23 08:51 UTC, shizhMSFT commented
The `AutoRemoveReferrers` flag was introduced in #653

2024-01-24 10:20 UTC, Wwwsylvia approved these changes
LGTM

2024-01-24 10:21 UTC, Wwwsylvia commented
Wondering if this is a `refactor`?

2024-01-25 11:33 UTC, shizhMSFT approved these changes
LGTM

2024-01-25 11:37 UTC, shizhMSFT requested changes

2024-01-25 11:37 UTC, shizhMSFT commented on content/oci/oci.go
> +	// unreferenced sucessor blobs and referrers. Tagged manifests will not be
```suggestion
	// unreferenced successor blobs and referrers. Tagged manifests will not be
```

2024-01-25 11:37 UTC, shizhMSFT commented on content/oci/oci.go
>  	// deleted.
Consider the following wording to reduce ambiguity
```suggestion
	// (unreferenced) blobs created by the Delete() operation. This includes the
	// referrers and the unreferenced successor blobs of the deleted content.
	// Tagged manifests will not be deleted.
```

2024-01-26 03:17 UTC, shizhMSFT approved these changes
LGTM

2024-01-26 03:20 UTC, Wwwsylvia approved these changes
LGTM

2024-01-26 03:20 UTC, merged