Issue templates
oras-project/oras-go pull request #716
Opened 2024-02-27 20:16 UTC by dextrot

This PR fixes #641 

- Adds issue templates for: `Bug report`, `feature request` and the config file for the templates.
![Screenshot from 2024-02-28 01-44-18](https://github.com/oras-project/oras-go/assets/131444479/0b7264d3-aecf-4eea-9fe6-6ba30012ea7c)

2024-02-27 20:17 UTC, dextrot commented
added the issue templates here @FeynmanZhou @shizhMSFT

2024-02-28 02:34 UTC, FeynmanZhou commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +        Thank you for reporting bugs to ORAS-GO!
We can use the term `ORAS Go library` or `oras-go` here

2024-02-28 06:20 UTC, dextrot commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +        Thank you for reporting bugs to ORAS-GO!
```suggestion
        Thank you for reporting bugs to ORAS Go library!
```

2024-03-11 08:31 UTC, shizhMSFT commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +      description: "You can use the command `oras version` to get it."
This also applies to `feature-request.yaml`.

2024-03-11 09:02 UTC, FeynmanZhou commented on .github/ISSUE_TEMPLATE/feature-request.yaml
> +      label: "What is the version of your ORAS CLI"
```suggestion
      label: "What is the version of your oras-go"
```

2024-03-11 09:03 UTC, FeynmanZhou commented on .github/ISSUE_TEMPLATE/feature-request.yaml
> +      label: "Why is this needed for ORAS?"
```suggestion
      label: "Why is this needed for oras-go?"
```

2024-03-11 09:03 UTC, FeynmanZhou commented on .github/ISSUE_TEMPLATE/feature-request.yaml
> +      description: "You can use the command `oras version` to get it"
Remove this description

2024-03-11 09:07 UTC, FeynmanZhou requested changes
Thanks @dextrot . Please do not replicate the ORAS issue template here as they have different functionalities. PTAL at my comments above

2024-03-11 09:07 UTC, dextrot commented on .github/ISSUE_TEMPLATE/feature-request.yaml
> +      description: "You can use the command `oras version` to get it"
```suggestion
   
```

2024-03-11 09:12 UTC, dextrot commented on .github/ISSUE_TEMPLATE/feature-request.yaml
> +      description: "You can use the command `oras version` to get it"
removed this description

2024-03-11 09:15 UTC, dextrot commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +      description: "You can use the command `oras version` to get it."
```suggestion
```

2024-03-11 09:15 UTC, dextrot commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +      label: What is the version of your ORAS CLI?
```suggestion
      label: What is the version of your oras-go library ?
```

2024-03-11 09:19 UTC, dextrot commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +      description: "Please also attach logs here using `--debug` flag."
@shizhMSFT can we put the description like : `description: "Please also attach logs here ."` ?

2024-03-26 08:27 UTC, Wwwsylvia commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +      description: "Please also attach logs here using `--debug` flag."
> can we put the description like : description: "Please also attach logs here ." ?

This sounds good to me.

2024-03-26 08:28 UTC, Wwwsylvia commented
@dextrot Thanks for the contribution! Could you address the remaining comments and rebase?

2025-03-10 10:26 UTC, dextrot commented
> Hi @dextrot , would you like to continue on this?

yes, let me address the remaining comments

2025-04-29 03:40 UTC, qweeah commented
![image](https://github.com/user-attachments/assets/553f9499-f09d-418c-b4ad-545ae90436a4)
Is there anything wrong with the CI? I saw it add and then remove the `stale` label. I think the latter operation is not preferred?

2025-07-14 10:45 UTC, closed without merging